services:

  mysql:
    image: mysql:8.0
    container_name: medicorex-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: medicorex_db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: medicorex-api

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=medicorex_db;user=root;password=root123"

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
    external: true
    name: 2ea609acb2eacb24fc112a4a3d4d5ee7559d7a38fdae9a828d780953352f1683